In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 0])

In [3]:
np.outer(a, a)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [4]:
np.kron(a, a)

array([0, 0, 0, 0, 1, 0, 0, 0, 0])

In [6]:
b = np.array([[1, -1, 0, 0], [-1, 2, -1, 0], [0, -1, 2, -1], [0, 0, -1, 1]])

In [7]:
b.shape

(4, 4)

In [8]:
np.linalg.inv(b)

LinAlgError: Singular matrix

In [9]:
b = np.array([[1, 2], [2, 1]])

In [10]:
np.linalg.eig(b)

(array([ 3., -1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [11]:
def fun(text):
    return text == text[::-1]

In [15]:
print(fun('1231'))

False


In [16]:
def account():
    return {"available":10}
def deposit(account, cash):
    account["available"] = account["available"] + cash
    return account["available"]

def withdraw(account, cash):
    account["available"] = account["available"] - cash
    return account["available"]

    


In [17]:
acc = account()
deposit(acc, 10)
deposit(acc, 201)
out = withdraw(acc, 100)

In [18]:
out

121

In [19]:
def f(x):
    x/=2
    return x

def g(x, y):
    x*=y +2
    return x

def h(x, y):
    return x*y

In [20]:
print(g(f(4), h(3, 2)))

16.0


In [22]:
class Ex(object):
    def __init__(self, x, y, z):
        self._x = x
        self._y = y
        self._z = z
        
    def px(self):
        print(self._x)
    
    def py(self):
        print(self._y)
    def pz(self):
        print(self._z)
    

In [24]:
Ex(1, 2).py()

TypeError: __init__() missing 1 required positional argument: 'z'

In [25]:
def my_deco(f):
    def inner_my(i=0):
        print("comv", end=",")
        f()
        
        if i==0:
            inner_my(1)
        else:
            f()
            print("max", end=",")
            
        print("relu", end=",")
    return inner_my
            

In [26]:
@my_deco
def decorated():
    print("drop", end=",")

In [27]:
decorated()

comv,drop,comv,drop,drop,max,relu,relu,

In [38]:
def draw(n):
    for i in range(n):
        print("*** " * (n-1) + "*")
        print("|" * (n) + "|")
    print("*** " * (n-1) + "*")    

In [39]:
draw(5)

*** *** *** *** *
||||||
*** *** *** *** *
||||||
*** *** *** *** *
||||||
*** *** *** *** *
||||||
*** *** *** *** *
||||||
*** *** *** *** *


In [40]:
try:
    if int("1") is 1:
        raise "someerroe"
    else:
        print("sefuhsf")
except "someerroe":
    print("123")

TypeError: catching classes that do not inherit from BaseException is not allowed

In [49]:
s = "1234"
f = []
for i in s:
    f.append(i)

In [50]:
f1 = np.array(f)

In [51]:
f1

array(['1', '2', '3', '4'], dtype='<U1')

In [46]:
for j in f1:
    if f1[j] == f1[j+1]:
        flag = 1
    else:
        flag = 0

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [57]:
for j in range(len(f1)):
    if f1[j] == f1[j+1]:
        flag = 1
    else:
        flag = 0

IndexError: index 4 is out of bounds for axis 0 with size 4

In [62]:
s = "1234"

In [63]:
sorted(s) == list(range(min(s), max(s)+1))

TypeError: must be str, not int

In [64]:
min(s)

'1'

In [65]:
max(s)

'4'

In [66]:
range(min(s), max(s)+1)

TypeError: must be str, not int